name: Bookmark CI

on:
  push:
    branches-ignore: [master]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: cd src/ && ./gradlew connectedCheck
